version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: sa
      DB_PASSWORD: prodPassword123
      JWT_SECRET: prodSecretKeyForJWTTokenGenerationAndValidationInStudentManagementAPI2025Production
      H2_CONSOLE_ENABLED: false
    volumes:
      - h2_data:/data
      - app_logs:/logs

volumes:
  h2_data:
  app_logs:
